version: '3.7'
services:
  db:
    image: postgres:12-alpine
    volumes:
    - ./data:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=db
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=53hf29ncdu308
    ports:
    - 3306:5432